name: Metrics
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  
jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@v3.19
        with:
          token: ${{ secrets.GH_TOKEN_2023 }}
