name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.19
        with:
          token: ${{ secrets.GH_TOKEN_2023 }}

          # Options
          user: Raed667
          template: classic
          base: header
          config_timezone: Europe/Paris
          plugin_habits: yes
          plugin_habits_days: 100
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_trim: yes
